### PR TITLE
prevent compiler errors on SDK 10.0.19041.0 Libs

### PR DESCRIPTION
**Pull request by suuhm**
prevent compiler errors in Virual Studio (Win10) by definition: PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY on Windows 10 Systems with stable SDK : 10.0.19041.0.

Missing in winnt.h OS < Win11:
```
+    typedef struct _PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY {
+      __C89_NAMELESS union {
+        DWORD Flags;
+        __C89_NAMELESS struct {
+          DWORD EnforceRedirectionTrust : 1;
+          DWORD AuditRedirectionTrust : 1;
+          DWORD ReservedFlags : 30;
+        };
+      };
+    } PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY, 
*PPROCESS_MITIGATION_REDIRECTION_TRUST_POLICY;
```

### CODE REVIEW

**Comment by xwnb** [comment]
Thanks for your fix. Could we upgrade `CustomBuildTool` to support VS 2022/Win 11 with latest SDK as well ([CustomBuildTool/Utils.cs](https://github.com/processhacker/processhacker/blob/master/tools/CustomBuildTool/Utils.cs))? it would be better.

**Comment by dmex** [comment]
>  support VS 2022

It has to actually be released. The directory paths and registry keys are all preview names.

**Comment by dmex** [comment]
> stable SDK : 10.0.19041.0

We shouldn't support outdated SDKs since these changes will just be added then deleted over and over?

**Comment by xwnb** [comment]
> Thanks for your fix. Could we upgrade `CustomBuildTool` to support VS 2022/Win 11 with latest SDK as well ([CustomBuildTool/Utils.cs](https://github.com/processhacker/processhacker/blob/master/tools/CustomBuildTool/Utils.cs))? it would be better.

VS 2022 is released today. Do we have plan to support?

**Comment by Biswa96** [comment]
There is already a fix with latest commits.

**Comment by xwnb** [comment]
> There is already a fix with latest commits.

Wow, so quick. 👍

**Review by nszhsl — APPROVED** [review]

**Review by nszhsl — APPROVED** [review]

**Review by nszhsl — APPROVED** [review]
ok

**Comment by dmex** [comment]
Fixed with the latest SDK 👍

**Comment by Ishmaeel** [comment]
I struggled with this for an embarassingly long time, so I would like to add a footnote for other noobs like me:

The "latest SDK" that @dmex mentions is `Windows 10 SDK (10.0.20348.0)`. Install it from Visual Studio installer.

**Comment by avoidik** [comment]
@Ishmaeel a tiny addition to your perfect answer

```bash
# roll-back to vs2019 in all projects at once
find ./processhacker -type f -iname '*.vcxproj' -exec sed -i 's|v143|v142|g' '{}' +;
# disable spectre-mitigated libraries in all projects at once
find ./processhacker -type f -iname '*.vcxproj' -exec sed -i 's|<SpectreMitigation>Spectre</SpectreMitigation>|<SpectreMitigation>false</SpectreMitigation>|g' '{}' +;
```

**Pull request closed without merging**
