### PR TITLE
Visitors Badge

### PR DESCRIPTION
**Pull request by itsmeshibintmz**
Added Visitors badge to repository readme.

### CODE REVIEW

**Review by dmex — APPROVED** [review]

**Comment by dmex** [comment]
@jxy-s Do you see any issues having this?

**Comment by jxy-s** [comment]
Seems reasonable to me. Wish there was a GitHub insights API for this, maybe there is one? This counter is a pretty simple implementation that doesn't account for history prior to the counter creation. But this is cool for now.

**Comment by itsmeshibintmz** [comment]
Thank you.

**Comment by jxy-s** [comment]
Looked a bit closer at the provider here. `vercel.app` seems to be collecting a lot information on traffic. Is @itsmeshibintmz is there another API provider you would suggest? `shield.io` is the go-to for this stuff.

Otherwise I think I'm going to have to revert this change.

**Comment by diversenok** [comment]
I also had a similar thought. But doesn't GitHub cache images? I see that viewing the page loads the content from `githubusercontent.com`, but there are no requests to `vercel.app`.

**Comment by itsmeshibintmz** [comment]
> . @itsmeshibintmz is there another API provider you would suggest? `shield.io` is the go-to for this stuff.

'll update soon.

**Pull request merged**
