### PR TITLE
phnt: Add structure definition for SystemSupportedProcessorArchitectures

### PR DESCRIPTION
**Pull request by Biswa96**
Ask me anything, I have done the _homework_ 🤓

### CODE REVIEW

**Comment by Biswa96** [comment]
I don't have that one. AFAIK, it's not the stable Windows SDK version.

**Comment by Biswa96** [comment]
AFAIK, it's not the stable Windows SDK version.

**Comment by dmex** [comment]
> this is defined in winnt.h of 22000 SDK

That structure is for Win32:

```
typedef struct _WOW64_ARCHITECTURE_INFORMATION {
    DWORD Machine : 16;
    DWORD KernelMode : 1;
    DWORD UserMode : 1;
    DWORD Native : 1;
    DWORD Process : 1;
    DWORD ReservedZero0 : 12;
} WOW64_ARCHITECTURE_INFORMATION;

WOW64_ARCHITECTURE_INFORMATION=Windows.Win32.System.SystemInformation
```

SYSTEM_SUPPORTED_PROCESSOR_ARCHITECTURES_INFORMATION is the correct structure for NT.


> Ask me anything, I have done the homework

Why the double struct typedef?

**Comment by Biswa96** [comment]
> Why the double struct typedef?

😁 Don't know. Just got that from combase.pdb.

**Comment by Biswa96** [comment]
>this is defined in winnt.h of 22000 SDK

OK, I have remove the structure definition.

**Comment by dmex** [comment]
> OK, I have remove the structure definition.

It's the correct structure.... The winnt.h type is for kernel32.

**Comment by Biswa96** [comment]
> It's the correct structure.... The winnt.h type is for kernel32.

OK, re-added it.

**Review by dmex — APPROVED** [review]

**Pull request merged**
